import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins , Open_Sans } from "next/font/google";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/themeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400", "500",
    "600", "700", "800", "900",
  ],
  style: ["normal", "italic"],
  variable: "--font-inter",
  display: "swap"
});


const openSans = Open_Sans({
 subsets: ["latin"],
  weight: ["300","400","500","600","700","800"],
  style: ["normal", "italic"],
  variable: "--font-OpenSans",
  display: "swap",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
  <html lang="en">
  <head>
    <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch(e) {}
              })()
            `,
          }}
        />

  </head>
  <body>
    <ThemeProvider>{children}</ThemeProvider>
  </body>
</html>
  );
}